# load("@crate_index//:defs.bzl",
#      "aliases", "all_crate_deps")
load("@rules_rust//rust:defs.bzl",
     "rust_binary", "rust_library", "rust_test")

rust_binary(
    name = "corpus",
    srcs = glob(["*.rs"]),
    edition = "2018",
    # proc_macro_deps = all_crate_deps(proc_macro = True),
    deps = [ # all_crate_deps(normal = True) + [
        "@crates//:ansi_term",
        "@crates//:anyhow",
        "@crates//:clap",
        "@crates//:ctrlc",
        "@crates//:difference",
        "@crates//:lazy_static",
        "@crates//:regex",
        "@crates//:walkdir",
        "//src/runtime/bindings/rust:tree-sitter"],
    # visibility = ["//visibility:public"]
)

